layout_spectrum: 0.8547013567654544
typography_spectrum: 0.26241904454029136
color:
  lightness: 0.10543626788588666
  brandColors:
    - '#105B63'
    - '#FFFAD5'
    - '#FFD34E'
    - '#DB9E36'
    - '#BD4932'
  saturation: 0.522139136324277
  brandStrength: 0.9511691472603764
  rhythmicContrast: 0.5007725995803934
name: TejaPhotoholics
analytics: {}
purpose:
  - type: contact
    url: 'tel:9704006608'
    label: Call Us
  - type: external
    url: 'https://www.facebook.com/tejamamidiphotography/'
    label: Visit us on facebook
github: true
description: >-
  Photography is a reality so subtle that it becomes more real than reality.  ―
  Alfred Stieglitz
author:
  name: ' © 2017 Team Teja-Photoholics. | Maintained by Team Teja Photoholics'
  url: 'http://teamtejaphotoholics.com/'
  email: g.vijaysudheer@gmail.com
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
content: []
navigation:
  - name: Travel Diaries
    id: dc284739-50df-408c-8208-764c8123a64b
    type: content
  - name: Wedding Moments
    id: eb0ebed9-ff3b-434a-b48c-7d1b6c759ea4
    type: content
  - name: Life around me
    id: c0da1fd2-8c63-4ec7-99ae-1b568249a5f0
    type: content
content_rating:
  adult: false
opengraph: {}
title: Teja Photoholics
url: 'http://teamtejaphotoholics.com/'
