name: TejaPhotoholics
analytics: {}
purpose:
  - type: contact
    url: 'tel:9704006608'
    label: Call Us
  - type: external
    url: 'https://www.facebook.com/tejamamidiphotography/'
    label: Visit us on facebook
github: true
description: >-
  Photography is a reality so subtle that it becomes more real than reality.  ―
  Alfred Stieglitz
author:
  name: ' © 2017 Team Teja-Photoholics. | Maintained by Team Teja Photoholics'
  url: 'http://teamtejaphotoholics.com/'
  email: g.vijaysudheer@gmail.com
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
content: []
navigation:
  - id: dc284739-50df-408c-8208-764c8123a64b
    name: Travel Diaries
    type: content
  - id: eb0ebed9-ff3b-434a-b48c-7d1b6c759ea4
    name: Wedding Moments
    type: content
  - id: c0da1fd2-8c63-4ec7-99ae-1b568249a5f0
    name: Life around me
    type: content
layout_spectrum: 0.7859869328080354
color:
  lightness: 0.4303736986580425
  brandColors:
    - '#105B63'
    - '#FFFAD5'
    - '#FFD34E'
    - '#DB9E36'
    - '#BD4932'
  saturation: 0.4909131738270568
  brandStrength: 0.2392098309686131
  rhythmicContrast: 0.9270435599778954
content_rating:
  adult: false
typography_spectrum: 0.376801264750135
opengraph: {}
title: Teja Photoholics
url: 'http://teamtejaphotoholics.com/'
