layout_spectrum: 0.7859869328080354
typography_spectrum: 0.376801264750135
color:
  lightness: 0.4303736986580425
  brandColors:
    - '#105B63'
    - '#FFFAD5'
    - '#FFD34E'
    - '#DB9E36'
    - '#BD4932'
  saturation: 0.49091317382705685
  brandStrength: 0.2392098309686131
  rhythmicContrast: 0.9270435599778954
github: true
name: TejaPhotoholics
navigation:
  - name: Travel Diaries
    id: dc284739-50df-408c-8208-764c8123a64b
    type: content
  - name: Wedding Moments
    id: eb0ebed9-ff3b-434a-b48c-7d1b6c759ea4
    type: content
  - name: Life around me
    id: c0da1fd2-8c63-4ec7-99ae-1b568249a5f0
    type: content
title: Teja Photoholics
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/dbf2f341-fc8d-46cd-adfc-8cc3941e498f.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/dbf2f341-fc8d-46cd-adfc-8cc3941e498f.jpg
    metadata:
      datePublished: null
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: >-
  Photography is a reality so subtle that it becomes more real than reality.  ―
  Alfred Stieglitz
purpose:
  - type: contact
    url: 'tel:9704006608'
    label: Call Us
  - type: external
    url: 'https://www.facebook.com/tejamamidiphotography/'
    label: Visit us on facebook
url: 'https://thegrid.ai/tejaphotoholics/'
author:
  name: Vijay Sudheer
  email: g.vijaysudheer@gmail.com
